### ISSUE TITLE
module specific commands

### ISSUE THREAD

**Issue by andragan** [creolab/laravel-modules#105]
is this working? I have tried by following the instructions from the [readme] (https://github.com/creolab/laravel-modules#commands-1)  but when I run
```
php artisan modules.incident:incRecommendationExpiryService
```
it always respond with
```
[InvalidArgumentException]
There are no commands defined in the "modules.incident" namespace.
```
'incident' is my module name, and 'incRecommendationExpiryService' is the command name.
I think I'm doing something wrong, so I tried searching in https://github.com/bstrahija/laravel-modules-example, but seems like there are no implementation of this 'module specific commands' there?

**Comment by GiovanniK** [comment]
Hi Andragan,

I have the same problem and also I cannot seem to fix it. Does someone else have an idea why this isn't working?

Giovanni

**Comment by GiovanniK** [comment]
Hi Andragan,

I have found the solution to this. What I did is the following:

Create the command:
`php artisan command:make  --path=app/modules/Vote/commands --namespace=App\Modules\Vote\Commands --command=modules.Vote:cleanOldLinks cleanOldLinks`

After that I put this in my module.json (NOTE: don't forget to use \\ instead of \): 
`"command": "App\\Modules\\Vote\\Commands\\cleanOldLinks"`

Now I did php artisan dump-autoload and I tried to use the module using `php artisan modules.Vote:cleanOldLinks` and it worked!

I can see that this issue was created in April, I do not know if you still need the solution for this. 

Giovanni
